name: brew_crew_app
description: A new Flutter project app with a database (Firebase Firestore) and an authentication system (using Firebase auth).

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A Flutter plugin to use the Firebase Authentication API.
  firebase_auth: ^0.15.4

  # A Flutter plugin to use the Cloud Firestore API.
  cloud_firestore: ^0.13.1

  # A mixture between dependency injection (DI) and state management, built with widgets for widgets.
  provider: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
